### ISSUE TITLE
Models in seperate files

### ISSUE THREAD

**Issue by Lyla-Fischer** [ahopkins/pydiggy#6]
* PyDiggy version: latest master
* Python version: 3.7
* Operating System: Ubuntu 16.04

### Description

I have an application where I would like to define multiple models that reference each other, but store them in different files. Python has issues with this because of circular imports, but it *should* be solvable by [refraining from importing the name](https://docs.python.org/3/faq/programming.html#what-are-the-best-practices-for-using-import-in-a-module) and importing the module only. However, this doesn't work with the current type annotation system. 

One of the lines that is referenced in the stacktrace([168](https://github.com/ahopkins/pydiggy/blob/cfdf387a8dc4f11f93286ce52fcc885517db1fd6/pydiggy/node.py#L161)) has a TODO on it, saying that it might benefit from some clean-up. 

### What I Did

I altered basic.py so that models were contained in separate files [here](https://github.com/ahopkins/pydiggy/commit/8184d5f5d46b997ad638d3dfadfd8b879a3c2f7a)

```
>python basic.py
Traceback (most recent call last):
  File "basic.py", line 25, in <module>
    por = seperate_model_file.Region(name="Portugal")
  File "/home/lyla/Projects/pydiggy/pydiggy/node.py", line 168, in __init__
    self.__class__, globalns=globals(), localns=localns
  File "/usr/local/lib/python3.7/typing.py", line 973, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/local/lib/python3.7/typing.py", line 260, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/local/lib/python3.7/typing.py", line 464, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'basic' is not defined

```

**Comment by Lyla-Fischer** [comment]
Do you have ideas on how I could clean up that module so that the circular references work? I haven't exhausted my google-foo yet, but I wanted to write an issue in case you had thoughts.

**Comment by ahopkins** [comment]
Yes, one thing that pydiggy needs is for the definition of a mode to be defined in the current context. I recently added the ability to pass context directly into the `hydrate` function, so that could help.

But, as for the circular referencing, this is where Python 3.7 really helps.

    from __future__ import annotations 

See [PEP 563](https://www.python.org/dev/peps/pep-0563/)

**Comment by ahopkins** [comment]
Also, and I haven't tried, you might also try using a string annotation instead

    class Foo(Node):
        bar: "Bar"

I have not tried this, but I think it would work.

**Comment by ahopkins** [comment]
**`main.py`**
```python
from cities import City
from states import State


def name(city):
    if city.state:
        return f"{city.name.title()}, {city.state.abbreviation.upper()}"
    else:
        return city.name.title()


if __name__ == "__main__":
    boston = City(name="Boston")
    ma = State(name="Massachusetts", abbreviation="MA")
    boston.state = ma

    city_name = name(boston)
    print(city_name)
```

**`cities.py`**
```python
# from __future__ import annotations
from pydiggy import Node


class City(Node):
    name: str
    state: "State"
```

**`states.py`**
```python
from __future__ import annotations
from pydiggy import Node


class State(Node):
    name: str
    abbreviation: str
```

I confirmed that you can either:

1. Use `from __future__ import annotations`, or
1. Use a string annotation:

        state: "State"

Either way, it will print:

```
Boston, MA
```

**Comment by Lyla-Fischer** [comment]
Very cool, thanks!
